# Generated by Django 5.1.2 on 2024-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='car_mark',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('bmw', 'BMW'), ('audi', 'Audi'), ('mercedes', 'Mercedes-Benz'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan'), ('volkswagen', 'Volkswagen'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('lexus', 'Lexus'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('volvo', 'Volvo'), ('porsche', 'Porsche'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('fiat', 'Fiat'), ('peugeot', 'Peugeot'), ('renault', 'Renault'), ('mitsubishi', 'Mitsubishi'), ('acura', 'Acura'), ('infiniti', 'Infiniti'), ('lincoln', 'Lincoln'), ('cadillac', 'Cadillac'), ('buick', 'Buick'), ('mini', 'Mini'), ('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('bentley', 'Bentley'), ('rolls_royce', 'Rolls-Royce'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('maserati', 'Maserati'), ('mcLaren', 'McLaren'), ('bugatti', 'Bugatti'), ('pagani', 'Pagani')], max_length=50, null=True),
        ),
    ]
